name: Build and Push Docker to ACR

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug secret
      run: echo ${{ secrets.ACR_LOGIN_SERVER }}

    - name: Login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/iotapp:v1 .

    - name: Push image
      run: |
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/iotapp:v1